version: '3.8'
services:
  mavlink-serial:
    image: mavlink-serial:0.0
    container_name: mavlink-serial
    network_mode: host
    restart: always
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
    volumes:
      - ./src:/root/mavlink_ws/src
    devices:
      - /dev/c_board:/dev/c_board
    stdin_open: true
    tty: true
    group_add:
      - dialout
