services:
  potential-mavlink:
    build: .
    image: potential-mavlink
    container_name: potential-mavlink
    network_mode: host
    restart: always
    privileged: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
    volumes:
      - /dev:/dev
      - ./src:/app/src
